### PR TITLE
景點API開發

### PR DESCRIPTION
**Pull request by angelc1997**
陳安琪

文件規格 http://100.28.23.193:8000/docs

已開發API
http://100.28.23.193:8000/api/attractions?page=1
http://100.28.23.193:8000/api/attractions?page=0&keyword=劍潭
http://100.28.23.193:8000/api/attractions?page=0&keyword=北
http://100.28.23.193:8000/api/attraction/10
http://100.28.23.193:8000/api/mrts

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
- images field should be an array containg all the image URLs for each attractons.
- nextPage field should be null in the last page. For example, nextPage field of http://100.28.23.193:8000/api/attractions?page=4 and http://100.28.23.193:8000/api/attractions?page=1&keyword=%E5%8C%97 should be null.

**Comment by angelc1997** [comment]
Modified the error of nextPage null response and the array type of images.

**Review by cwpeng — CHANGES_REQUESTED** [review]
- null is not "null".
- images field is named incorrectly.

**Comment by angelc1997** [comment]
Modified error of Null data and Naming

**Review by cwpeng — CHANGES_REQUESTED** [review]
We should not get all data from database and do pagination in our code. (how about 1,000,000 rows). We should do pagination by SQL Limit feature directly.

**Comment by angelc1997** [comment]
Modified pagination issue

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
