### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by angelc1997**
陳安琪

http://100.28.23.193:8000/
http://100.28.23.193:8000/attraction/10

Test Example  (Already created in database)
account：test@gmail.com
password：test

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
- Always use password input elemnt for password input.
- I cannot sign in by email/password I just signed up.

**Comment by angelc1997** [comment]
Modified password input issue.
Modified sign in error.

Already created testing account (Just note for avoiding using)
- an@gmail.com
- aa123@gmail.com
- aaaa@aaaa.com

**Review by cwpeng — CHANGES_REQUESTED** [review]
We should check user sign-in status by calling User API, not just check localStorage in the front-end. (how about I put any text in localStorage through developer tools?)

**Comment by angelc1997** [comment]
Modified User API

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
